# -*- coding: utf-8 -*-
"""
Created on Mon Aug 27 14:44 2018

@author: Xiangjie Zhao

These codes define the functions for computing 
cell distance and cell co-appearring times
"""

import numpy as np
import pandas as pd
from itertools import combinations


def distance(data):
    """Computing cell-pair distance before converting
    to distance rate
    
    Parameters
    ______________
    data: the dataframe cleaned

    Returns
    ______________
    df_rate: a dataframe containning 3 columns, cellA, cellB
    and the percent distant
    """  
    cell_number = data.shape[0]
    data_values = data.iloc[:,:3]
    
#    #compute distance
#    df = pd.DataFrame(columns = ['cellA', 'cellB', 'distance'])
#    for i in range(cell_number):
#        for j in range(i+1, cell_number):
#            dis = np.linalg.norm(data_values.iloc[i,:] - data_values.iloc[j,:])
#            df_row = pd.DataFrame([[data.iloc[i,3], data.iloc[j,3], dis]],
#                                  columns = ['cellA', 'cellB', 'distance'])
#            df = df.append(df_row)
            
    #compute  distance rate
    df_rate = pd.DataFrame(columns=['cellA', 'cellB', 'distance_rate'])
    for i in range(cell_number):
        df_rate_i = pd.DataFrame(columns=['cellA', 'cellB', 'distance_rate'])
        for j in range(cell_number):
            dis = np.linalg.norm(data_values.iloc[i,:] - data_values.iloc[j,:])
            df_rate_row = pd.DataFrame([[data.iloc[i,3], data.iloc[j,3], dis]],
                              columns = ['cellA', 'cellB', 'distance_rate'])
            df_rate_i = df_rate_i.append(df_rate_row)    
        #remove 0 distance
        df_rate_i = df_rate_i[df_rate_i.iloc[:,2] != 0]
        dis_i = df_rate_i['distance_rate']
        #scale distance to 0
        df_rate_i['distance_rate'] =  (dis_i-dis_i.min()) / (dis_i.max() -dis_i.min())     
        df_rate = df_rate.append(df_rate_i)    
    
    return df_rate
    

def coexistence(picture_num):
    """Computing coexistence times of two cell 
    
    Parameters
    ______________
    picture_num: the number of the first few pictures
    chosen from all the pictures

    Returns
    ______________
    result_list: a dataframe containning 3 columns, cellA, cellB
    and their coexisting times 
    """  
    count_dict = {}
    for n in range(picture_num):
        data = pd.read_csv('./test/t%03d-nuclei.csv' % (n+1), sep=',', header=None)
        cell_combination = list(combinations(data.iloc[:,3],2))
        for comb in cell_combination:
            if comb in count_dict:
                count_dict[comb] = count_dict[comb]+1
            else:
                count_dict[comb] = 1
    pair = np.array(list(count_dict.keys()))
    count = np.array(list(count_dict.values()))
    stack_array = np.vstack([pair.transpose(), count]).transpose()
    df_cotimes = pd.DataFrame(stack_array, columns=['cellA', 'cellB', 'coexist_time'])
#    df_corate = df_cotimes.copy()
#    df_corate.columns = ['cellA', 'cellB', 'coexist_rate']
#    df_corate.iloc[:,2] = pd.to_numeric(df_corate.iloc[:,2]) / picture_num 
#    
    return df_cotimes
    

def near_cell(picture_num, df_cotimes, cut_off = .1):
    """Computing the counts of near cell pairs
    according to the cutoff denoted by user
    
    Parameters
    ______________
    picture_num: the number of the first few pictures
    chosen from all the pictures
    cut_off: the threshold to choose near cell pairs
    df_cotimes: the dataframe generated by funtion coexistence(),
    storing times of coexistence of cell pairs
    
    Returns
    ______________
    df_near: a dataframe similar to df_cotimes,
    recording the counts of near cell pairs
    """  
    for file_num in range(picture_num):
        df_dis = pd.read_csv('./distance_rate/t%03d-dis.csv' % (file_num+1), sep=',', header=None)
        index = df_dis.iloc[:,2] > cut_off
        df_remove = df_dis[index].iloc[:,:-1]
        #drop redoundance
        for i in range(df_remove.shape[0]):
            df_remove.iloc[i,:] = list(df_remove.iloc[i,:].sort_values())
        df_remove = df_remove.drop_duplicates([0,1])
        #drop counts that is larger than cute_off from total coexistence times
        for j in range(df_remove.shape[0]):
            cellA = df_remove.iloc[j,0]
            cellB = df_remove.iloc[j,1]
            index = (df_cotimes.iloc[:,0] == cellA) & (df_cotimes.iloc[:,1] == cellB)
            recount = int(df_cotimes[index].iloc[0,2]) - 1
            df_cotimes[index] = [cellA, cellB, recount]
        print('progress rate: %.1f%%' % ((file_num +1)/picture_num*100), end='\r')
    df_near = df_cotimes
    return df_near
